owenfarrell/vscode-vault

.travis.yml
README.md

Migrated from BitHound to CodeClimate

---

src/commands/login/native.ts

Removed Validator for Native Tokens

---

package-lock.json
package.json
src/model.ts

Upgraded node-vault to v0.9.12

---

package-lock.json
package.json
src/commands/connect.ts
src/config/index.ts
src/config/load.ts
src/extension.ts
src/model/session.ts
src/view/server.ts

Re-added support for configuring trusted authorities

---

package-lock.json
package.json
src/model/window.ts

Replaced clipboard API with VSCode provided implementation

---

README.md

Re-added Build Status Badge to README

---

package.json

Ordered commands in view item menu

---

package.json
resources/dark/command/disconnect.svg
resources/light/command/disconnect.svg
src/extension.ts
src/view/treedataprovider.ts

Added vault.disconnect command

---

src/commands/connect.ts
src/model/session.ts
src/view/treedataprovider.ts

Retain reference to login callback function from VaultSession

---

package.json
src/adaptors/index.ts
src/commands/connect.ts
src/commands/login/base.ts
src/commands/login/github.ts
src/commands/login/index.ts
src/commands/login/native.ts
src/commands/login/userpass.ts
src/extension.ts
src/model/config.ts
src/model/index.ts
src/model/session.ts
src/view/server.ts
src/view/treedataprovider.ts

Preserve list of Vault servers across VSCode restarts

---

src/commands/connect.ts
src/view/treedataprovider.ts

Prevent creation of TreeView elements with duplicate IDs

---

src/commands/write.ts
src/extension.ts
src/view/path.ts
src/view/secret.ts

Validate mount point when writing a path

---

package-lock.json
package.json
webpack.config.js

Check for circular dependencies at build time

---

src/adaptors/kv2.ts

Conditionally parse read response

---

src/commands/connect.ts
src/extension.ts
src/model/config.ts
src/model/index.ts
src/model/session.ts
src/view/server.ts
src/view/treedataprovider.ts
src/view/treeitem.ts

Improve consistency of connect command

---

package.json
src/commands/login/index.ts
src/commands/login/ldap.ts
src/extension.ts
src/model/session.ts
src/view/index.ts
src/view/path.ts
src/view/secret.ts
src/view/server.ts
src/view/shell.ts
src/view/treeitem.ts

* Gracefully remove sessions that never connected
* Add LDAP login support

Improve user interface consistency

---

src/commands/delete.ts
src/commands/list.ts
src/commands/login/base.ts
src/commands/login/github.ts
src/commands/login/ldap.ts
src/commands/login/native.ts
src/commands/login/userpass.ts
src/commands/read.ts
src/commands/write.ts
src/extension.ts
src/model/session.ts
src/model/window.ts
src/view/server.ts
src/view/treedataprovider.ts

Remove vscode namespace extension

---

src/adaptors/kv2.ts
src/model/session.ts
src/util/index.ts
src/view/path.ts
src/view/server.ts
src/view/treeitem.ts
test/browse/kv1.ts
test/browse/kv2.ts
test/test.ts

Prevent engine prompt when browsing a path to an existing mount point

---

src/extension.ts
src/view/treedataprovider.ts

Add server element to TreeView on login failure

---

src/extension.ts

Rename local variable to avoid conflict with upper scope

---

package.json
src/commands/copy.ts
src/commands/index.ts
src/commands/read.ts
src/extension.ts
src/view/secret.ts

User Interface Updates

---

.github/workflows/build.yml

Skip GitHub Actions on documentation updates

---

package.json

Limit connection buttion to Vault view title menu

---

src/commands/login/github.ts

Add new token format to user input validator

---

package-lock.json
package.json
src/adaptors/kv2.ts
src/commands/connect.ts
src/commands/login/github.ts
src/commands/login/ldap.ts
src/commands/login/native.ts
src/commands/login/userpass.ts
src/commands/write.ts
src/extension.ts
src/model/config.ts
src/model/session.ts
src/view/server.ts
src/view/treedataprovider.ts

Add support for namespaces
